### ISSUE TITLE
Is there any specific schedule for code releasing.

### ISSUE THREAD

**Issue by Adenialzz** [baaivision/DIVA#1]
Hi, DIVA is a nice work and thanks for open-sourcing. I wonder is there any specific schedule for code releasing.

**Comment by Rubics-Xuan** [comment]
Thank you very much for your interest in our work! We are expediting the open-sourcing process and expect to release the training/evaluation code within the next week or so. Please stay tuned!

**Comment by Rubics-Xuan** [comment]
We have released all the source code as scheduled. Thank you for all your interests in our work!

**Comment by Adenialzz** [comment]
Nice work ! Thanks.
