### ISSUE TITLE
Looking forward to releasing CLIP model weights 

### ISSUE THREAD

**Issue by dulibubai** [baaivision/DIVA#3]
Nice works!!!  Looking forward to releasing CLIP model weights !

**Comment by NielsRogge** [comment]
Indeed, if they pushed to HF, it would be great to link them to https://huggingface.co/papers/2407.20171 so that people can discover the models from the paper page.

See here on how to do that: https://huggingface.co/docs/hub/en/model-cards#linking-a-paper

**Comment by Rubics-Xuan** [comment]
Many thanks for your great interests on our work! We will release all the CLIP model weights very soon to serve the research community and facilitate everyone to use our DIVA-tuned CLIP models. Please stay tuned!

**Comment by sipie800** [comment]
Great work! Will you guys release the trained MLLM demo trained on the CLIP? That would be exciting to get an instant insight of the excellect granularity in a MLLM task. Thanks.

**Comment by Rubics-Xuan** [comment]
Please refer to LLaVA(https://github.com/haotian-liu/LLaVA) for the MLLM training details.

**Comment by sipie800** [comment]
Few people can afford training a MLLM while most people afford doing inference.
