### ISSUE TITLE
the weights trained based on ViT-B-16.pt

### ISSUE THREAD

**Issue by syc1336** [baaivision/DIVA#6]
Will you be making public the weights trained based on ViT-B-16.pt? In many application scenarios, base-clip proves to be more practical. We would greatly appreciate it if the results of training base-clip were made available.

**Comment by Rubics-Xuan** [comment]
Thanks for your great interests! We currently haved not trained DIVA architecture based on ViT-B-16.pt. We may consider adding relevant results in the future, please stay tuned.
