### ISSUE TITLE
Does params in table1 reported in the paper just contain the visual parameter number?

### ISSUE THREAD

**Issue by Yang-bug-star** [baaivision/DIVA#8]
Hello, I found that the number of parameters of the visual component of clip-vit-L-14 is just 289.88 M. If we conside the actual size the parameters occupy, they occupy 289.88*2=579.76 M bytes( considering fp16), neither of which is consistent with the reported params.

**Comment by GuiQuQu** [comment]
the CLIP model in this model not only contain the visual model, but also the text model (I get the message by running code). but the use model actually is visual model
